### ISSUE TITLE
Error:'res.users' object has no attribute 'plan_id'

### ISSUE THREAD

**Issue by jorsea** [yelizariev/website-addons#10]
By step after configuration is complete, when I open odoo.Locat/page/start and enter any letters, click Try now, prompted the following error.

Error:'res.users' object has no attribute 'plan_id'

**Comment by jorsea** [comment]
Sorry, there is the SaaS-tools module error message.

**Comment by yelizariev** [comment]
https://github.com/yelizariev/odoo-saas-tools/issues/9
