### ISSUE TITLE
Error on product Export when using module website_sale_search_custom

### ISSUE THREAD

**Issue by okuryan** [yelizariev/website-addons#11]
Hi Ivan,

We have found an error in website_sale_search_custom module. Maybe you can help in fixing it. Note that your module is used in https://apps.openerp.com/apps/modules/8.0/website_search_suggestion/ that i spaid module that is purchased by our customer. I'm not sure if you are related to that module, but maybe you can helpю

SO basically problem is following:
1. Install module website_sale_search_custom
2. Go to menu "Sales -> Products" and try to export product templates. See below screenshot:
![screen shot 2015-08-31 at 18 18 53](https://cloud.githubusercontent.com/assets/2680904/9582260/e5cc31e2-500c-11e5-8491-17d7cfedc710.png)
3. Now click on Export and see below error:
![screen shot 2015-08-31 at 18 21 56](https://cloud.githubusercontent.com/assets/2680904/9582288/34968304-500d-11e5-968a-865d068b2e56.png)

Also copying the text:
Odoo Server Error
Traceback (most recent call last):
  File "/opt/openerp/odoo/addons/web/controllers/main.py", line 70, in wrap
    return f(*args, **kwargs)
  File "/opt/openerp/odoo/addons/web/controllers/main.py", line 1460, in index
    return self.base(data, token)
  File "/opt/openerp/odoo/addons/web/controllers/main.py", line 1435, in base
    ids = ids or Model.search(domain, 0, False, False, context)
  File "/opt/openerp/odoo/openerp/http.py", line 908, in proxy
    result = meth(cr, request.uid, *args, **kw)
  File "/opt/openerp/odoo/openerp/api.py", line 241, in wrapper
    return old_api(self, *args, **kwargs)
TypeError: search() takes at most 5 arguments (8 given)

Why I think that problem is related to website_sale_search_custom ?
We commented out this  3 lines of code and Export started to work. https://github.com/yelizariev/website-addons/blob/8.0/website_sale_search_custom/models.py#L36

Just for your information - we are using Odoo 8:
# git rev-parse HEAD
9ef5e40278b317a022410d418a751d162523005b

**Comment by yelizariev** [comment]
Good catch, thank you for reporting!
