### ISSUE TITLE
[8.0] website_files - pager (next button) for pictures is no longer working

### ISSUE THREAD

**Issue by michaelkarrer81** [yelizariev/website-addons#4]
if i install website_files on odoo 8.0 ab00527f0776e26f82182547e0065fa22cd4d7cb the pager of the image tab in the modal box is no longer working: 

If you press on "Next" Button for next page of pictures nothing happens and the button greys out.

**Comment by yelizariev** [comment]
Thanks for reporting.

I've fixed it in old repo https://github.com/yelizariev/addons-yelizariev/issues/7 and forgot to update it here
