### ISSUE TITLE
Redirect /page/homepage to /

### ISSUE THREAD

**Issue by erwin-bas-solutions** [yelizariev/website-addons#6]
I try to redirect /page/homepage to /, but then i get "To many redirects" error. Any idea how to best redirect /page/homepage to root?

**Comment by yelizariev** [comment]
I don't know why / is redirected to /page/homepage. Maybe you use some old version?

Also, I've updated website_redirect module, so now it check rules only if error 404 is occurred. So, now it's imposible to redirect  /page/homepage to /, because  /page/homepage doesn't return 404
